opencollective/opencollective-website

frontend/src/components/PublicGroupSignup.js, frontend/src/components/SaveButton.js, frontend/src/components/Tiers.js, frontend/src/containers/DonatePage.js, frontend/src/containers/PublicGroup.js, frontend/src/css/base/forms.css, frontend/src/css/components/Button.css, frontend/src/css/components/ExpenseForm.css, frontend/src/css/main.css, frontend/src/ui/strings.json, server/lib/render.js
Quick and dirty because this is time sensitive.
But we should ideally use a i18n library like this one https://github.com/yahoo/react-intl
The v1 relies on `Mixins` and that's not ideal for using it within components.
So we should use for the v2 (in Release Candidate 1) as it is introducing a good amount of improvements and upgrading from v1 to v2 will be a pain that I would rather try to avoid.
=> page in french for LaPrimaire.org

circle.yml
=> Force NODE_ENV=test on circleci just to be sure 

circle.yml, package.json, scripts/install_apt_get_debs.sh
As suggested here: https://discuss.circleci.com/t/add-ability-to-cache-apt-get-programs/598/5
=> Cache Google Chrome deb package for faster circleci build

frontend/src/components/ExpenseItem.js, frontend/src/lib/format_currency.js, test/unit/lib/format_currency.js
At least one collective (ISPCWA) needs this right now. Likely there are others as well.
=> allow negative signs for balance

frontend/src/components/public_group/PublicGroupHero.js
Requires https://github.com/OpenCollective/api/pull/278
=> using the background image of the collective if any

frontend/src/components/Metric.js, frontend/src/components/public_group/PublicGroupHero.js, frontend/src/components/public_group/PublicGroupWhoWeAre.js, frontend/src/components/public_group/PublicGroupWhyJoin.js, frontend/src/css/containers/PublicGroup.css
Logo now on top and a few other design tweaks
=> Public group design updates

frontend/src/css/components/DonationPicker.css
As much as I like the look and feel of the currency in the box, we would need to customize the currency and jsx doesn't support it as far as I can tell.
=> removing $ from other field

frontend/src/components/public_group/PublicGroupThanksV2.js, frontend/src/containers/PublicGroup.js, frontend/src/css/components/PublicGroupThanks.css
The url that is shared (the public collective url) includes a `referrerId` attribute with the id of the user making the publication.
=> ShareIcon component added to PublicGroupThanksV2 component

frontend/src/components/ImagePicker.js, frontend/src/components/public_group/PublicGroupSignupV2.js, frontend/src/css/components/ImagePicker.css
Infinite loop bug is resolved
@ character in twitter handle is now a valid handle and is parsed
Widen dot list so as to neatly show more dots
Detects missing or 404 images and fixes self and makes sure it doesn't repeat on the same image src
=> Fixed bug; made more fault tolerant

frontend/src/components/UserPhoto.js, frontend/src/css/components/UserPhoto.css, server/config/production.json, server/controllers/banner.js
Recording a page view as per 
And making the logos of the sponsors rectangular instead of rounded:
=> Fix event tracking and logo for sponsors

server/controllers/banner.js, server/routes.js
Thanks @dasilvacontin @sedubois for the code review, here are the fixes :-)
=> fixes for code review

frontend/src/components/UserPhoto.js, frontend/src/css/components/UserPhoto.css
Also fixed loader showing behind transparent images
=> Contains avatar image instead of covering its container

frontend/src/components/public_group/PublicGroupHero.js, frontend/src/css/containers/PublicGroup.css
Original PR https://github.com/OpenCollective/website/pull/191
=> Backers count

frontend/src/containers/DonatePage.js, frontend/src/containers/PublicGroup.js, frontend/src/ui/tags.js, frontend/src/ui/vat.js, server/utils/api_url.js
Fixes https://github.com/OpenCollective/OpenCollective/issues/68
=> French version for LesBarbares

frontend/src/css/customization.css, frontend/src/css/main.css
This adds a `customization.css` file to contain any customizations needed for a PublicGroup (currently gulpjs).  Every style is prefixed with the group slug as a namespace which is inserted into the className of the PublicGroup component (added by #208).  This file is imported at the end of the `main.css` file.
=> add css customizations for the gulpjs PublicGroup

frontend/src/css/customization.css
Some more changes for the customization.  I also made some mistakes in my previous rules that altered the styles of some links and made them invisible (white on white).
=> add more customization for the gulp page

frontend/src/components/Checkbox.js, frontend/src/components/CustomTextArea.js, frontend/src/components/ImagePicker.js, frontend/src/components/on_boarding/ContributorPicker.js, frontend/src/components/on_boarding/ContributorPickerItem.js, frontend/src/components/on_boarding/OnBoardingHeader.js, frontend/src/components/on_boarding/OnBoardingStepCreate.js, frontend/src/components/on_boarding/OnBoardingStepPickCoreContributors.js, frontend/src/css/components/Checkbox.css, frontend/src/css/components/ContributorPicker.css, frontend/src/css/components/CustomTextArea.css, frontend/src/css/components/ImagePicker.css, frontend/src/css/containers/OnBoarding.css, frontend/src/css/main.css
ImagePicker was tweaked to allow custom labeling and image preview size
Added Checkbox general purpose component
Added CustomTextArea general purpose component, includes visual max-length counter and eases styling of placeholder text by not relying on pseudo selectors, (the placeholder is its own element)
=> Updates for On Boarding Container and related components

frontend/src/css/containers/PublicGroup.css
Fixes https://github.com/OpenCollective/OpenCollective/issues/79
=> background position to 50% 50%

frontend/src/containers/PublicGroup.js
For issue https://github.com/OpenCollective/opencollective-website/issues/239
=> Removed extra brace

frontend/src/components/AsyncButton.js, frontend/src/components/public_group/DonationDistributor.js, frontend/src/css/containers/PublicGroup.css
…still shows
Added code to try and keep the Tier Button single line
Also added style updates for PublicGroup (rounded tier buttons as originally designed)
=> Added padding so when button label overflows the text in tier box

frontend/src/css/containers/PublicGroup.css
For issue https://github.com/OpenCollective/opencollective-website/issues/251
=> Added css fix

server/controllers/banner.js
PubNub is only 64px wide on the Apex repo because of this bug.
=> sometime the tier is singular/plural

package.json, server/app.js
See #232 for original PR.
Opening this one here for CI.
=> use WEBSITE_PORT var for custom port when starting server; closes #230

frontend/src/actions/github/fetch_repos.js
For https://github.com/OpenCollective/OpenCollective/issues/117
=> Added member type, removed sort by stars

frontend/src/components/UserPhoto.js, frontend/src/css/components/UserPhoto.css
For https://github.com/OpenCollective/OpenCollective/issues/97
=> Changed .UserPhoto bg color from #f9fafa to #e9eaea

frontend/src/ui/strings.json
made some tweaks in open source open collective.
=> updated lang for opensource

server/routes.js
When we deploy this, we need to change the slug of `consciousnesshackingsf` to `chsf` and `consciousnesshackingsv` to `chsv`
=> adding redirects for consciousnesshackingSF/SV

frontend/src/containers/ProfilePage.js, frontend/src/css/components/UserPhoto.css
For https://github.com/OpenCollective/OpenCollective/issues/138
=> Uses user.isOrganization, to show a rounded or square avatar container

frontend/src/components/on_boarding/OnBoardingHero.js
For issue https://github.com/OpenCollective/OpenCollective/issues/123
=> Added tos link under connect github button

test/unit/components/OnBoardingStepCreate.js
For https://github.com/OpenCollective/opencollective-website/pull/302#issuecomment-227489182
=> Unit test for on boarding step create component

frontend/src/components/ProfilePhoto.js, frontend/src/components/UserPhoto.js, test/unit/components/ProfilePhoto.js
Fixes https://github.com/OpenCollective/OpenCollective/issues/149
=> making sure we proxy user.avatar through https

package.json, server/controllers/banner.js, server/lib/utils.js, server/middlewares.js, test/e2e/github_apply.js, test/server/banner.spec.js
- Added the button become a backer/sponsor
- Making sure we don't display avatars that don't load
- Using caching to avoid having to generate the png every time
=> Banner.svg v2

frontend/src/components/CollectiveCard.js, frontend/src/containers/ProfilePage.js, frontend/src/css/containers/ProfilePage.css, frontend/src/css/main.css
A branch with the same name exists in OpenCollective/api repository, it provides the data that a CollectiveCard expects: https://github.com/OpenCollective/opencollective-api/pull/470
The API branch **MUST** be merged first.
------------------------
@asood123 Here is a screenshot of the CollectiveCard: 
On the left is a card with default logo and background.
On the right is a card with yeoman's data filled in.
=> Replaced ProfileCard with CollectiveCard component.

server/controllers/banner.js, server/routes.js, server/views/bannerjs.hbs
=> first iteration for the opencollective footer banner

frontend/src/actions/users/fetch_by_id.js, frontend/src/client.js, frontend/src/components/LoginEmailForm.js, frontend/src/containers/Leaderboard.js, frontend/src/containers/Login.js, frontend/src/containers/LoginTopBar.js, frontend/src/containers/Subscriptions.js, frontend/src/css/containers/Leaderboard.css, frontend/src/css/containers/Login.css, frontend/src/css/main.css
Continuing work on LoginTopBar: https://github.com/OpenCollective/OpenCollective/issues/154
=> Login part 2

frontend/src/css/components/CollectiveCard.css
use className `CollectiveCard--large` to revert to original (larger) size, default will be the smaller card
=> Smaller CollectiveCard component

frontend/src/assets/images/homepage-bg.svg, frontend/src/components/homepage/MailChimpInputSection.js, frontend/src/containers/HomePage.js, frontend/src/css/components/MailChimpInputSection.css, frontend/src/css/containers/HomePage.css, frontend/src/css/main.css
Set overall opacity of homepage bg to 70%
Minor 'css collision' fixes
Added new component homepage/`MailChimpInputSection`
=> Added mailchimp input for waiting list in homepage

frontend/src/containers/HomePage.js, frontend/src/containers/LoginTopBar.js, frontend/src/css/components/CollectiveCard.css, frontend/src/css/components/MailChimpInputSection.css
For https://github.com/OpenCollective/opencollective-website/pull/350#issuecomment-233961015
+ Css alignment fix for safari
+ topbar anchors to waitinglist section in homepage
=> Fix css for safari

frontend/src/components/public_group/PublicGroupHero.js, frontend/src/containers/HomePage.js, frontend/src/containers/LoginTopBar.js, frontend/src/containers/ProfilePage.js, frontend/src/containers/PublicGroup.js, frontend/src/css/containers/ProfilePage.css, frontend/src/css/containers/PublicGroup.css
Replaced topbar in `HomePage`, `ProfilePage` and `PublicGroup` components to use `LoginTopBar` component
=> Topbar replacement (w/LoginTopBar)

frontend/src/components/public_group/PublicGroupWhoWeAre.js, frontend/src/containers/PublicGroup.js
We need a compact version of the collective card to make this manageable. @carlosascari @erickrico
=> support showing all collectives in a supercollective automatically

frontend/src/css/components/LoginTopBar.css
Found a miss alignment, live!
Fix
=> Top padding reduced to 5px

frontend/src/containers/Faq.js, frontend/src/css/containers/Faq.css, frontend/src/css/main.css, frontend/src/routes.js, server/routes.js
For https://github.com/OpenCollective/OpenCollective/issues/181
=> Faq move from website-static repo

frontend/src/containers/PublicGroup.js
For https://github.com/OpenCollective/OpenCollective/issues/185#issuecomment-234661223
`.center` === `text-align: center;`
=> Center cards

frontend/src/css/components/DonationDistributor.css
=> fixed specificity so it is scoped to .DonationDistributor-header parent className

server/controllers/banner.js, test/data/mocks.json, test/server/banner.spec.js
with slug of the collective.
Fixes https://github.com/OpenCollective/OpenCollective/issues/69
=> automatically add utm_source tracking when redirecting

frontend/src/ui/strings.json
changed button to Pay for Rides! and become a member to Why Pay for Rides?
=> update strings for FreeRideToVote

frontend/src/components/Tiers.js, frontend/src/containers/DonatePage.js, frontend/src/css/containers/DonatePage.css
For https://github.com/OpenCollective/OpenCollective/issues/201
- Includes Responsive CSS
- `group.mission` collapses Mission line if missing
- `group.host.name` collapses website link/button if missing
=> Update /donate page's design

frontend/src/components/PublicFooter.js, frontend/src/css/components/PublicFooter.css
- Hides logo when screen is small, removes floats and centers links
- Alignment fix between footer logo and links
=> Responsive css for footer

frontend/src/components/public_group/PublicGroupThanksV2.js, frontend/src/containers/DonatePage.js, frontend/src/css/base/media-queries.css, frontend/src/css/containers/PublicGroup.css
Just add a `tweet` attribute in the definition of a tier.
=> allow to have a custom tweet to share depending on the tier

frontend/src/css/components/LoginTopBar.css
Fixes the following issues found:
1. Profile menu misalignment when user is not logged in. The root of the bug here is that the component would align with the margin of the `ul.LoginTopBar-Links` element. When in mobile, the element is hidden so the margin that aligns the menu button is missing.
Fix removes the margin from the `ul` element and moves it to the `div.LoginTopBar-nav` element in the form of padding.
2. Profile/Avatar logo image repeats and is not explicitly centered.
Fix does not allow logo image to repeat and centers horizontally and vertically.
=> Css fixes for LoginTopBar 

frontend/src/containers/HomePage.js
I'd like to include the idea of a shared mission and make it about people not about an association.
=> propose new tagline

frontend/src/components/public_group/AmountPicker.js, frontend/src/components/public_group/DonationDistributor.js, frontend/src/css/components/DonationDistributor.css
For https://github.com/OpenCollective/OpenCollective/issues/199
When set to `true` it will render the disclaimer under the donate button
=> Added showDisclaimer property for DonationDistributor component

frontend/src/components/public_group/PublicGroupPending.js, frontend/src/containers/PublicGroup.js
Created `PublicGroupPending` component.
=> Moved Pending view out from PublicGroup into its own component

frontend/src/components/public_group/PublicGroupWhoWeAre.js, frontend/src/css/components/PublicGroupWhoWeAre.css, frontend/src/css/main.css
Created PublicGroupWhoWeAre.css in order to seperate style tied to PublicGroupIntro
=> Refactored PublicGroupWhoWeAre component

frontend/src/containers/PublicGroup.js
- Hoisted Literals above the class definition as constants
- Hoisted non-methods, as private/protected functions above class definition
- Re-ordered logic, and code in general to reduce overall vertical size
=> Refactored PublicGroup component

frontend/src/containers/Faq.js
=> updated faq

frontend/src/components/homepage/MailChimpInputSection.js, frontend/src/containers/HomePage.js
For https://github.com/OpenCollective/opencollective-website/pull/344#issuecomment-233714320
=> Turned become a sponsor cta link into a mailchimp input section

frontend/src/components/public_group/DonationDistributor.js, frontend/src/components/public_group/PublicGroupWhyJoin.js, frontend/src/containers/EditCollective.js, frontend/src/css/containers/EditCollective.css
Why Join section is now editable, however only an image can be uploaded.
=> Added whyJoin editable section

frontend/src/components/Grid.js, frontend/src/css/components/Grid.css, frontend/src/css/main.css
A Grid based off of [basscss](http://www.basscss.com/) supporting
- Static layout
- Responsive layout
- Flexbox
In a single package.
Here is a sample showing how the Grid can be used:
```jsx
import Grid, { Column } from 'Grid';
<Grid flex>
<Column auto>
<Grid>
<Column className='Column-6'>
A
</Column>
<Column className='Column-6'>
B
</Column>
<Grid flex className='author'>
<Column>
C 
</Column>
<Column auto>
D             
</Column>
</Grid>
<Column className='Column-xs-12 Column-lg-4'>
E
</Column>
</Grid>
</Column>
</Grid>
```
=> Added Grid and Column components

frontend/src/containers/Login.js, frontend/src/css/containers/Login.css
=> Login Facelift

frontend/src/components/public_group/PublicGroupHero.js, frontend/src/lib/export_file.js
Fixes https://github.com/OpenCollective/OpenCollective/issues/161
=> add export members in csv feature if member

frontend/src/components/ConnectAuthProviderButton.js, frontend/src/containers/ConnectProvider.js, frontend/src/css/components/PublicFooter.css, frontend/src/css/containers/ConnectProvider.css, frontend/src/css/main.css, frontend/src/routes.js, test/e2e/connect_github_button.js, test/e2e/connect_twitter_button.js
For https://github.com/OpenCollective/OpenCollective/issues/235
=> Created ConnectProvider container

frontend/src/components/ImagePicker.js, frontend/src/components/ImageUpload.js, frontend/src/components/UserPhoto.js, frontend/src/containers/ProfilePage.js, frontend/src/css/containers/ProfilePage.css
=> update avatar from profile page if logged in

frontend/src/containers/Login.js, test/unit/containers/Login.js
=> Showing a much nicer email sent screen than the default notification

frontend/src/containers/PublicGroup.js
we only ask for name, but we automatically split it in firstName and lastName
=> splitting firstName and lastName after donation

frontend/src/ui/expenseCategories.js
@xdamman I merged this PR https://github.com/OpenCollective/opencollective-website/pull/471
Without realizing it was failing, now all PRs will fail on CircleCI. 
Please merge to fix
=> Removed dupes

config/default.json, frontend/src/components/ContentEditable.js, frontend/src/components/CustomTextArea.js, frontend/src/components/Markdown.js, frontend/src/components/public_group/PublicGroupWhoWeAre.js, frontend/src/css/components/PublicGroupWhoWeAre.css, test/unit/components/Markdown.js
Added editable state to our markdown component.
It starts out as showing markdown. onClick will turn it editable. onBlur will switch back to markdown
=> allows editing of long description in markdown

frontend/src/ui/strings.json
I changed 'contributor' to Board Member for consistency in latest push.
=> update rga strings

frontend/src/containers/AddGroup.js, frontend/src/containers/NewGroup.js, frontend/src/css/base/input.css, frontend/src/joi_schemas/newGroup.js
(why join is part of the long description now)
=> Need to agree to ToS + removed whyJoin

server/src/lib/utils.js
=> resizing to png if png src

server/src/controllers/banner.js, server/src/views/bannerjs.hbs
Before:
After:
How to use it:
<script src="https://opencollective.com/webpack/banner.js?header=false"></script>
=> improving the banner.js

frontend/src/components/CollectiveCard.js, frontend/src/components/RelatedGroups.js, frontend/src/components/public_group/PublicGroupHero.js, frontend/src/containers/PublicGroup.js, frontend/src/css/components/CollectiveCard.css, frontend/src/lib/utils.js
=> Custom styles in the collective card

frontend/src/components/SponsoredCard.js, frontend/src/containers/ProfilePage.js
=> showing total amount donated as a backer / sponsor on profile page

frontend/src/components/Markdown.js, frontend/src/containers/DonatePage.js, frontend/src/css/containers/DonatePage.css, frontend/src/css/containers/PublicGroup.css
=> support for youtube video embed in long description

.gitignore, frontend/src/components/Mosaic.js, frontend/src/components/collective/CollectiveMembers.js, frontend/src/components/public_group/PublicGroupContributors.js, frontend/src/components/public_group/PublicGroupMembersWall.js, frontend/src/css/components/Mosaic.css, frontend/src/css/main.css
=> Mosaic for members and backers

server/src/controllers/banner.js
=> making sure we don't crash if we can't load sponsor image

frontend/src/containers/Transactions.js
=> show avatars on /ubie/donations

frontend/src/components/UserAvatarRow.js, frontend/src/css/components/UserAvatarRow.css
This fixes when number "+365" is overlapping with avatars.
=> fix css issue on small screens for user avatar row

frontend/src/components/SponsoredCard.js
=> fix to show the total donations on the profile page

frontend/src/lib/utils.js
Fix for https://github.com/OpenCollective/OpenCollective/issues/275
=> if we don't need to transform the image, no need to proxy it

frontend/src/components/ExpenseForm.js, frontend/src/containers/SubmitExpense.js
this fixes submitExpense issue
=> don't reset expense form on load

server/src/controllers/banner.js, server/src/routes.js, test/server/banner.spec.js
unless `?button=false` passed as a parameter
=> make sure we show the become a backer/sponsor button 

frontend/src/components/DonationPicker.js, frontend/src/components/Tiers.js, frontend/src/containers/Collective.js, frontend/src/containers/OnBoarding.js, test/unit/actions/form/append_donation.js, test/unit/containers/Collective.js
This fixes the bug reported by @piamancini where the `interval` would not go back to the initial interval of the presets after opening the "Other".
=> Fix donate other

frontend/src/components/UserAvatarRow.js
this will help reduce bandwidth
=> reduce bandwidth

frontend/src/components/SubscriptionItem.js, frontend/src/containers/Subscriptions.js
Needs api PR to be merged: https://github.com/OpenCollective/opencollective-api/pull/763
=> update frontend with new data model

frontend/src/components/SubscriptionItem.js, frontend/src/containers/Subscriptions.js, frontend/src/css/components/SubscriptionItem.css
UI tweaks to make this page easier to use: https://github.com/OpenCollective/OpenCollective/issues/224
=> cleanup subscriptions page interface

frontend/src/containers/NewGroup.js, frontend/src/routes.js, server/src/routes.js
This allows OTF to share a link like opencollective.com/opentechfund/apply?groupType=default
=> allow skipping the menu for otf

server/src/routes.js
to get the data of the collective in json format
=> added new route /:collective.json 

frontend/src/containers/DonatePage.js, frontend/src/containers/Ledger.js, frontend/src/containers/Response.js, frontend/src/routes.js, server/src/routes.js
`/:collective/:verb(donate|pay|contribute)/:amount(/:interval)/:description`
=> allow for customizing the button in custom url

frontend/src/reducers/transactions.js
Related: https://github.com/OpenCollective/opencollective-api/pull/809
=> using transaction.type instead

frontend/src/components/UserPhoto.js
Fixes https://github.com/OpenCollective/OpenCollective/issues/313
=> linking the avatars to their profile page

frontend/src/components/UserCard.js, frontend/src/components/UserPhoto.js
jsx doesn't link anchor tags outside of div
=> remove anchor from outside of div

frontend/src/containers/DonatePage.js, test/unit/containers/DonatePage.js
Closing https://github.com/OpenCollective/opencollective-api/issues/769
=> redirect after /donate?redirect=

frontend/src/components/collective/CollectiveActivityItem.js, frontend/src/components/collective/CollectiveExpenseItem.js
when you hover over "2 months ago", this will show "January 9, 2017"
=> show exact date

frontend/src/containers/Notification.js, frontend/src/containers/PaypalPreapprovalContainer.js, frontend/src/containers/StripeAuthContainer.js
bug fix for: https://github.com/OpenCollective/OpenCollective/issues/323
=> show success status and remove parameters from url

frontend/src/containers/LearnMore.js
I thought this looked a bit off, so I changed it.
=> Capitalized GitHub, added a period

frontend/src/components/PayButton.js, frontend/src/components/collective/CollectiveExpenseItem.js, frontend/src/containers/Ledger.js
Requires https://github.com/OpenCollective/opencollective-api/pull/857
=> show payout method and private notes if canViewReceipt

frontend/src/css/containers/Collective.css
=> Fixed the width style of 'img' in 'Markdown'

package.json, server/src/routes.js, test/server/api.json.js
Fixes https://github.com/OpenCollective/OpenCollective/issues/342
=> adding cors headers

frontend/src/containers/Discover.js, frontend/src/css/components/DiscoverSelect.css, test/e2e/expenses_page.js
Requires https://github.com/OpenCollective/opencollective-api/pull/858
=> default order by most popular, fix css for mobile

frontend/src/components/Tiers.js
Stripe transaction fee: 0.8% with $5 max.
See https://stripe.com/bitcoin
=> allow to accept bitcoin per collective

frontend/src/components/on_boarding/OnBoardingStepCreate.js, frontend/src/components/on_boarding/OnBoardingStepPickRepository.js, frontend/src/components/on_boarding/RepositoryPicker.js, frontend/src/containers/OnBoarding.js, frontend/src/joi_schemas/github.js, frontend/src/reducers/github.js
Automatically populates tags from github and also shows a field to edit them
=> show field for tags in the flow

frontend/src/components/Invoice.js, frontend/src/css/components/Invoice.css, server/src/controllers/transactions.js, server/src/routes.js
make sure we never bleed over a second page
=> updated PDF invoice layout

frontend/src/components/collective/CollectiveEvents.js, frontend/src/components/collective/CollectiveHero.js, frontend/src/containers/Collective.js
=> show events by default

frontend/src/components/Markdown.js, frontend/src/components/Tiers.js, frontend/src/components/collective/CollectiveHero.js, frontend/src/containers/DonatePage.js, frontend/src/css/components/YoutubeVideo.css, frontend/src/css/containers/DonatePage.css, frontend/src/lib/tiers.js
=> Allow youtube video in the description of a tier

frontend/src/containers/About.js
I'll revert in a couple of weeks.
=> change my title..don't ask

server/src/controllers/banner.js, test/data/mocks.json
Fixes https://github.com/opencollective/opencollective/issues/479
=> fix redirect from github for backers

frontend/src/containers/NewGroup.js
fixes https://github.com/opencollective/opencollective/issues/563
=> creator should be ADMIN of new collective

frontend/src/css/components/LoginTopBar.css, frontend/src/css/containers/HomePage.css
Fixes https://github.com/opencollective/opencollective/issues/1087
Preview:
=> Homepage: push search bar to full-width on mobile

frontend/src/containers/LoginTopBar.js, frontend/src/css/components/LoginTopBar.css
Fixes opencollective/opencollective#1105
Preview:
=> Display 'Create a Collective' link in ProfileMenu

frontend/src/components/on_boarding/OnBoardingStepCreate.js
Fixes https://github.com/opencollective/opencollective/issues/1137
=> OnBoarding: add checkbox for agreeing to host terms of service

frontend/src/components/Invoice.js
Fixes https://github.com/opencollective/opencollective/issues/1159
=> show the user address in invoice
