.babelrc
package.json

Transforms the imports so that the functions are cherry picked. From [`babel-plugin-lodash`'s README](https://github.com/lodash/babel-plugin-lodash):
Transforms:
```js
import _ from 'lodash';
import { add } from 'lodash/fp';
let add1 = add(1);
_.map([1, 2, 3], add1);
```
roughly to
```js
import _add from 'lodash/fp/add';
import _map from 'lodash/map';
let add1 = _add(1);
_map([1, 2, 3], add1);

Don't bundle unused lodash code

---

frontend/src/components/UserPhoto.js

If fails: preset avatar is used instead
otherwise the avatar image is set as the background
Quick Fix
Resolves `infinite loader` issue when the avatar links are invalid or missing

Attempts to load avatar image programmatically

---

frontend/src/components/public_group/PublicGroupHero.js
frontend/src/ui/strings.json

They are sorted ASC by tier.ranges[0]
0 backers of any tier, removes them from being displayed
Fixed bug where if currency had a space, it was treated as a digit by isNaN, using a safer regex test now. https://github.com/OpenCollective/OpenCollective/issues/65

Uses group.tiers to determine types of backers available

---

frontend/src/containers/PublicGroup.js

As a temporary solution for the GulpJS project (until https://github.com/OpenCollective/OpenCollective/issues/63 can be implemented), @xdamman and I discussed adding the `group.slug` as a class to the hero and then adding custom CSS based on it.

add group.slug to PublicGroup element

---

frontend/src/css/components/UserCard.css

When a sponsor didn't add a name .UserCard-name would collapse, a fixed height was used.
A gray rectangle bg from UserPhoto component was removed since it is visible even after an image is set when the UserCard is a sponsor, unlike any other tier where the image would cover the bg.

Set fixed height for UserCard name, removed UserPhoto avatar bg

---

test/unit/setup.js

(avoid error: Cannot read property 'clientId' of undefined' in `server/app.js`)

Allow running npm run test:server in dev again

---

README.md

Adding badges to README as visible here: https://github.com/OpenCollective/website/tree/badges
Could be added to `api` and `app` repos too. Slack could be added to `opencollective` repo.

Add badges for Slack, Gitter, David and Snyk

---

server/middlewares.js
server/routes.js

Determines if the error thrown because the api server is down
Also determines if api server is up, but fetching failed
Any other error is logged

Added middleware to catch uncaught errors

---

README.md
test/e2e/connect_account_page.js

Result: https://github.com/OpenCollective/opencollective-website/tree/badges

Fix badges after repo name change

---

frontend/src/actions/github/fetch_repos.js

Temporary fix, should cover most cases, 100 repositories are shown ordered from highest star count to least.
For completeness, some form of pagination should be implemented.
For https://github.com/OpenCollective/OpenCollective/issues/81#issuecomment-221390767

Fix set max repo fetch 100

---

frontend/src/containers/PublicGroup.js
frontend/src/css/containers/PublicGroup.css

For https://github.com/OpenCollective/OpenCollective/issues/129
Banner only displays when `group.slug` is `opensource`, when true the whyjoin section is hidden as well.

Added banner under PublicGroupWhoWeAre component in PublicGroup

---

frontend/src/css/containers/PublicGroup.css

You can see the bug live now: https://opencollective.com/opensource
The banner's width causes the Horizontal scroller show, this fixes it
@asood123  please merge this fix, its a css one-liner

Set box-sizing to border-box, banner causes h-scroll to show on page

---

frontend/src/components/UserPhoto.js
frontend/src/components/public_group/ContributorList.js
frontend/src/containers/PublicGroup.js
frontend/src/css/components/ContributorList.css
frontend/src/css/containers/PublicGroup.css
frontend/src/css/main.css

with a username as key and its value the total number of commits.
Modified UserPhoto so it listens to hover events.
For https://github.com/OpenCollective/OpenCollective/issues/122
As long as `group.data.githubUsers` is falsy it will not display. 
Contributors are sorted so core contributors are first followed by number of commits after.
Only commits are displayed, if additions and/or deletions are included they will be displayed as well.
@asood123 @boneskull  
`group.data` does not tell us whether a user is a core contributor or not. How can we determine core contributors?

Contributors are listed when group.data.githubUsers is an object:

---

frontend/src/components/on_boarding/OnBoardingStepCreate.js

For https://github.com/OpenCollective/OpenCollective/issues/140
I chose to disable the button temporarily in order to discourage multiple clicks, and not leave the user in a possible frozen state where they will have to refresh the page in order to continue.

Disables create button for 5 seconds

---

frontend/src/containers/HomePage.js

Map props to include `backerCount`, `sponsorCount` and `monthlyIncome`
Related:
- https://github.com/OpenCollective/opencollective-api/pull/478

Maps /homepage results so CollectiveComponent can display data in footer

---

frontend/src/assets/images/oc-logo-icon.svg
frontend/src/components/LoginTopBar.js
frontend/src/css/components/LoginTopBar.css
frontend/src/css/main.css

For https://github.com/OpenCollective/OpenCollective/issues/154
A single property `user` is accepted, if it is passed, then topbar shows a profile menu with the avatar and name of the user on the right hand side.
The component will collapse the avatar if it is falsy, so only the name shows when missing.
This is simply the component, it has not replaced the current public topbar anywhere.
To use it:
```js
import LoginTopBar from '../components/LoginTopBar';
const user = {
avatar: 'https://avatars2.githubusercontent.com/u/2263170?v=3&s=26', 
name: 'Ascari Gutierrez'
};
// When rendering
<LoginTopBar user={user} />
```
Using the new HomePage as an example by replacing the `OnBoardingHeader` component with `LoginTopBar`.

Added LoginTopBar component

---

server/controllers/banner.js
test/server/banner.spec.js

Links were opening inside the svg object, so adding a target to open them in a new tab fixes the issue.
I also fixed the url, to always have a link for every user (either the user's website or the OC slug url), because I believe it was another issue... Some users didn't have urls (@asood123 for example). Let me know if it was expected and I'll revert this part if needed.

Fix links in banner svg

---

frontend/src/css/components/CollectiveCard.css

Fix mentioned here: https://github.com/OpenCollective/opencollective-website/pull/345#issuecomment-233685548
NOTE: These are the maximum characters that will fit in each element:
**.CollectiveCard-name**
Max 27 characters. `text-overflow: ellipsis`
**.CollectiveCard-description**
Max 231 characters. `overflow: hidden`

Shorten description whitespace (and overall card height) by ~20px.

---

frontend/src/css/components/CollectiveCard.css

Assert height at 400px
Hide name
Align description vertically 
Hide first footer metric and center align other 2 footer metrics
**Assumptions**
+ A sponsor card does not display their name i.e `CollectiveCard-name`, as the logo should convey this info.
+ In a sponsor card, there are only two entries in the footer i.e `CollectiveCard-footer`, as oppose to the default 3. The **FIRST**, entry is the one that is hidden.
So far, here are the available styles a `CollectiveCard` can become:

Fix sponsor CollectiveCard

---

frontend/src/containers/Notification.js

When there is a `Notification` container rendered, there is no way to hide it.
Fix will hide notification, when component is clicked.

When clicking notification, close notification

---

frontend/src/actions/subscriptions/cancel.js
frontend/src/actions/subscriptions/get.js
test/unit/actions/subscriptions/cancel.js
test/unit/actions/subscriptions/get.js

This fixes `jwt malformed` error that users are seeing on canceling a subscription. We weren't passing the token properly.

token wasn't being passed properly

---

frontend/src/components/CollectiveCard.js

Currently the className `col col-4` from [basscss](http://www.basscss.com/#basscss-grid) is used to align 3 statistic blocks in the footer. When there are only 2 or 1 available statistic, an empty statistic block is added so alignment is preserved, the available statistic to the left, and two empty statistic blocks to the right.
This fix willl set the className `col col-x` where x is `12/number of statistics`. So no dummy elements are added and statistics are center aligned even when there are 2 or one statistic available to display.

Center align n-statistics in CollectiveCard footer

---

frontend/src/css/containers/DonatePage.css

Changed website link element to `inline-block` so it stretches with content
Related:
- https://github.com/OpenCollective/opencollective-website/pull/383

Fix DonatePage website link so it grows with the size of its content

---

frontend/src/components/discover/DiscoverSelect.js
frontend/src/containers/Discover.js

1. `DiscoverSelect`'s menu will now hide when clicking anywhere on the document other than the menu. 
2. Discovery Via Scrolling would fail on Chrome because of lack of compatibility, I used the following [StackOverflow answer](http://stackoverflow.com/a/33462363), and confirmed the fix on Chromium and Mozilla Firefox.

Fixes for Discover

---

frontend/src/containers/Discover.js
frontend/src/containers/HomePage.js
frontend/src/containers/LoginTopBar.js
frontend/src/routes.js
server/routes.js

For example: 
`/discover/meetup?sort=oldest`
`/discover?show=meetup&sort=oldest`
Url Param
**tag** Tag name to filter by (`/discover/:tag`)
Query Params
**show**: Tag name to filter by
**sort**: Sort direction only `oldest` & `newest` are valid, 
Also, `LoginTopBar` was modified so its *Discover* link now points to `/discover` page.

Discover can filter based on tag param and query params

---

package.json

[CircleCI is failing](https://circleci.com/gh/OpenCollective/opencollective-website/1998) with the following message: 
```
You have mistakenly installed the `babel` package, which is a no-op in Babel 6.
Babel's CLI commands have been moved from the `babel` package to the `babel-cli` package.
npm uninstall babel
npm install babel-cli
See http://babeljs.io/docs/usage/cli/ for setup instructions.
```

Replaced module `babel` with `babel-cli`

---

frontend/src/css/components/DonationDistributor.css

Fix will position disclaimer text relative to its own size, instead of a fixed distance.
(Tested on Chromium and Firefox)

Removed fixed top so it is relative to position

---

frontend/src/css/components/CollectiveCard.css

Not all letters would fit properly

Removed explicit height on the .CollectiveCard--name class

---

frontend/src/components/ExpenseItem.js

(instead of just the category which doesn't say much)
I would add a different field "Notes (private)" as an opportunity to justify the expense in a private way. See https://github.com/OpenCollective/OpenCollective/issues/234

showing the title of the expense if any

---

frontend/src/components/ExpenseForm.js
frontend/src/css/components/ExpenseForm.css

For https://github.com/OpenCollective/OpenCollective/issues/234
Added `CustomTextArea` for notes, the input only shows when payment method is not paypal
Added `DatePicke`r component for `incuredAt` date field, defaults to Today.

Added Notes and Date input

---

frontend/src/css/base/input.css
frontend/src/css/components/CustomTextArea.css
frontend/src/css/containers/Transactions.css

For https://slack-files.com/T0HSL38JD-F2ELW0R1P-53995bb984
@xdamman
On mobile it appears the `box-shadow` for the `CustomTextArea` component is missing. 
This may be a mobile browser quirk since:
- The bug could not be recreated while on Desktop, w/ Firefox and Chromium in normal and mobile modes.
- All Inputs have the same exact `box-shadow: inset 0 1px 3px 0 rgba(0,0,0,.2);` There is no reason for other elements to render the box-shadow and not the TextArea unless, it was a browser bug.
Fixes:
- Set explicit no background for `CustomTextArea` placeholder element, just to be sure its not being covered by this element.
- There was another minor css issue where the submit button had a fixed width, and would overflow if the screen was less than ~400px in width
- Set `-webkit-appearance: …

Removed fixed width of submit button

---

frontend/src/containers/Subscriptions.js

The links for leaderboard were hardcoded to point to opencollective.com - instead they should be relative.

Use relative link for leaderboard link

---

frontend/src/components/CollectiveCard.js
frontend/src/components/public_group/PublicGroupHero.js
frontend/src/css/components/PublicGroupHero.css
frontend/src/lib/utils.js

avoid downloading 5MB image to only show a 320px wide version of it in the CollectiveCard.

optimizing image size

---

frontend/src/css/components/ContentEditable.css
package.json

When hover over a editable component, it will be surrounded by a dotted border and will have a white background. 
The background and border will persist if the component has focus.

Added border and white bg for hover and focus states

---

frontend/src/actions/expenses/create.js
frontend/src/actions/groups/fetch_by_slug.js
frontend/src/actions/groups/update.js
frontend/src/actions/groups/updateMembers.js
frontend/src/actions/groups/updateSettings.js
frontend/src/actions/transactions/fetch_by_group.js
frontend/src/actions/transactions/fetch_by_id.js
frontend/src/actions/users/fetch_by_group.js
frontend/src/client.js
frontend/src/components/ContentEditable.js
frontend/src/components/public_group/AmountPicker.js
frontend/src/components/public_group/PublicGroupHero.js
frontend/src/components/public_group/PublicGroupWhoWeAre.js
frontend/src/containers/DonatePage.js
frontend/src/containers/PublicGroup.js
frontend/src/containers/SubmitExpense.js
frontend/src/containers/Transactions.js
frontend/src/lib/api.js
frontend/src/lib/schemas.js
frontend/src/reducers/groups.js
frontend/src/reducers/transactions.js
frontend/src/ui/expenseCategories.js
frontend/src/ui/vat.js
scripts/deploy.sh
test/unit/actions/groups/fetch_by_slug.js
test/unit/actions/transactions/fetch_by_group.js
test/unit/actions/transactions/fetch_by_id.js
test/unit/actions/users/fetch_by_group.js
test/unit/containers/PublicGroup.js
test/unit/reducers/groups.js

Slug is also a unique idea but it has the benefit of always being available in the URL.
This also makes it easier to handle the case of the redirect after login with `pushState`.
Today, it doesn't work and it shows a group page that is empty (the user needs to hard refresh the page). That's because the current page changes but it didn't get the opportunity to do a call to the API to turn the slug into a group id. We could handle that particular case differently but I figured it would be more elegant to use the `group.slug` everywhere. It's also easier to debug as a slug is more human readable than an id.
It also simplifies the custom categories for all wwcode groups and others.
I also took the opportunity to make our code works with the Redux Google Chrome Extension. It's pretty cool and …

Using group.slug instead of group.id to simplify things

---

frontend/src/components/Invoice.js
frontend/src/containers/PublicGroup.js
frontend/src/containers/PublicPage.js
frontend/src/containers/Transactions.js
frontend/src/routes.js
server/src/controllers/homepage.js
server/src/views/helpers/busted.js
server/src/views/pages/invoice.hbs

I found a more elegant solution to support a custom domain such as BrusselsTogether.org
I just force a default collective to show instead of the homepage and we make sure we don't induce the slug from the URL.
I also had to make sure we would load the CSS from a relative path, except for the invoice PDF.

default collective as homepage for custom domain

---

frontend/src/containers/Ledger.js
frontend/src/routes.js
frontend/src/selectors/router.js
server/src/routes.js

New route `/:slug/expenses/:expenseid/:action(approve|reject)` to automatically approve or reject an expense. The API will return an error if the logged in user doesn't have the right permissions.

new route to approve/reject expense automatically

---

frontend/src/containers/Login.js

user was confused when /login/:token?next=/login kept taking her back to login page. Now by default, if there is a token and redirect says '/login', it'll take you to homepage.

fix login redirect bug user hit on Friday

---

frontend/src/components/collective/CollectivePendingExpenses.js

If there is no unpaid expense, there is no link to get to the list of expenses.
See this thread: https://twitter.com/thetoxicarcade/status/822312267450490882

making sure we always show View All Expenses even if no pending ones

---

frontend/src/css/containers/About.css

Underneath "Our Founding Team" you're losing padding on that paragraph `<p data-reactid=".0.2.2">...</p>` above 900px
What makes the most sense for a quick n' dirty fix here is to simply remove that 600px media query, so you've always got 30px of padding on the ".About-container"
Cheers!

Awesome site, small oversight

---

frontend/src/css/containers/DonatePage.css

this fixes the issue where the logo would be cut off at the top
e.g. https://opencollective.com/sustainoss/donate/500

css fix for /donate page

---

frontend/src/containers/NewGroup.js

Also added host fee defined by parent host (in `group.settings.hostFeesPercent`, defaults to 5%) and added a new type "coop" as one user was suggesting on Twitter.
For a new host that wants and `/apply`, we need to create a group that has in its settings:
{
"HostId": Integer, // User Id of the Host User
"hostFeesPercent": 5, // optional: percentage for the host (default: 5)
"superCollectiveTag": "wwcode" // show all collectives that have the same tag on the page
}

add the tags of the host to the new collective

---

frontend/src/css/components/ImagePicker.css

Fix https://github.com/opencollective/opencollective/issues/350
Currently visitors (left) see a normal logo, but for editors / admins / core contributors (right) it is rounded in the view.
That is confusing especially for us because we recently had to change our logo from the round version to square because of a trademark reference. I even uploaded a version of our logo with appropriate margins next to the logo so it wouldn’t be caught by the rounding – unaware that users see the full logo anyway.
This edit removes the radius so it simply looks the same for both visitors/users and editors/admins.

Remove border-radius from logo preview to look same for editors and visitors

---

server/src/middlewares.js

If a user is both a core contributor and a backer, the `_.uniq(users, "id")` would randomly pick the user with the role core contributor or with the role backer. That's why they wouldn't always show up as backers.
Bug reported by https://opencollective.com/kaku

make sure users with multiple roles show up as backers

---

frontend/src/components/collective/CollectiveHero.js

This is just a first step. It will only show the link to create an event to core contributors.
Next step would be to allow any member (backer/sponsor included) to create an event (see https://github.com/opencollective/opencollective-api/pull/900) -- but we should think about how to communicate this to all core contributors, we don't want to take them by surprise.

add create event link to menu bar -- only for core contributors for now

---

frontend/src/components/collective/CollectiveLedger.js
frontend/src/components/collective/CollectiveTransactions.js

This makes sure that we are loading the new /transactions page instead of the old one.

link to the new /transactions page from the collective page

---

frontend/src/components/Invoice.js

The bill to was showing the name of the collective that received the money instead of the collective that gave the money (because we use the DEBIT Transaction)

bill to the collective that made the transaction

---

frontend/src/containers/Faq.js

Took out invoicing/address info for the Open Source Collective, because now each host can specify this info in 'expense policies'. The info in the FAQ should apply generally to all hosts.

Further update to the expenses FAQ section
